name: CI (pip)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Root directory
      run: |
        python -c "import rootpath; print(rootpath.detect())"
        python -c "import sys; import rootpath; print(sys.path); sys.path.append
        (rootpath.detect()); print(sys.path)"
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=astir
    - name: Upload coverage
      shell: pwsh
      run: coverage report -m